swagger: '2.0'
info:
  description: User related APIs
  version: "1.0.0"
  title: User related APIs
  contact:
    email: info@texastoc.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

host: api-texastoc.herokuapp.com
basePath: /api/v2

schemes:
 - http

paths:
  /users/login:
    post:
      summary: login
      description: login with email and password
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
        - name: credentials
          in: body
          description: user's email and password
          schema:
            required:
              - credentials
            properties:
              email:
                type: string
              password:
                type: string
      responses:
        201:
          description: logged in
          schema:
            required:
              - data
            properties:
              token:
                type: string
        400:
          description: invalid input

  /users/password/forgot:
    post:
      summary: forgot password
      description: will send an email with a code that is valid for five minutes
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
        - name: credentials
          in: body
          description: user's email and password
          schema:
            required:
              - credentials
            properties:
              email:
                type: string
      responses:
        201:
          description: created a code
          schema:
            required:
              - data
            properties:
              code:
                type: string
        404:
          description: email not found

  /users/password/reset:
    put:
      summary: reset password
      description: requires the code generated by the forgot password api
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
        - name: credentials
          in: body
          description: user's email and password
          schema:
            required:
              - credentials
            properties:
              email:
                type: string
              code:
                type: string
              password:
                type: string
              password2:
                type: string
      responses:
        204:
          description: updated password
        400:
          description: password do not match
        401:
          description: code not found or invalid
        404:
          description: email not found
